name: Release

on:
  push:
    branches:
      - master
      - develop
      - 'release/*'

jobs:
  release:
    name: Build & Publish
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Check PR labels action step
        id: labelcheck
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["create-release"]'
      - name: Continue only if the create-release label exists, fail otherwise.
        if: steps.labelcheck.outputs.result != 'true'
        run: exit 1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Avoid shallow clone so nbgv can do its work.
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x # SDK Version to use.
      - name: Build project
        run: dotnet build --configuration Release
      - name: Run dotnet tests
        run: dotnet test Daf.Core.Sdk.sln --configuration Release --nologo
      - name: Create the nuget package
        run: dotnet pack Daf.Core.Sdk/Daf.Core.Sdk.csproj --configuration Release --output Daf.Core.Sdk/bin/Release/Publish
      - name: Publish to Nuget
        run: dotnet nuget push Daf.Core.Sdk/bin/Release/Publish/**/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET }}
      - name: Setup Nerdbank.GitVersioning
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release/*' # Only run this step in master and release branches.
        id: nbgv
        uses: dotnet/nbgv@v0.4.0
      - name: Tag commit
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release/*' # Only run this step in master and release branches.
        uses: tvdias/github-tagger@v0.0.2
        continue-on-error: true # github-tagger will crash if the tag already exists. Not a problem, continue anyway.
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.nbgv.outputs.SimpleVersion }}
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          failOnError: true
          configuration: "configs/configuration.json"
          toTag: v${{ steps.nbgv.outputs.SimpleVersion }}
      - name: Create release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release/*' # Only run this step in master and release branches.
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.nbgv.outputs.SimpleVersion }}
          tag_name: v${{ steps.nbgv.outputs.SimpleVersion }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Move latest MajorMinor version tag
        uses: EndBug/latest-tag@v1.4.0
        with:
          tag-name: v${{ steps.nbgv.outputs.MajorMinorVersion }}
      - name: Move latest Major version tag
        uses: EndBug/latest-tag@v1.4.0
        with:
          tag-name: v${{ steps.nbgv.outputs.VersionMajor }}
